### ISSUE TITLE
Training pipeline [EPIC]

### ISSUE THREAD

**Issue by Shreyanand** [os-climate/aicoe-osc-demo#120]
This issue will be used to track all outstanding tasks required to complete the training pipeline. Demo 2 (issue #58) currently supports inference using pre-trained models.  For a complete demo, we should have the training pipeline in place as well. 

Issues:

- [ ] Write training notebooks #11 
- [ ] Explore Neural magic for a sparse model training #91 
- [ ] Integrate inference pipeline to work with training pipeline

**Comment by JeremyGohBNP** [comment]
@Shreyanand @chauhankaranraj Hello! I hope you enjoyed your days off! I am following up on the training pipeline implementation. How has it been going? Do you need additional info or material? Thanks for the update.

**Comment by chauhankaranraj** [comment]
> @Shreyanand @chauhankaranraj Hello! I hope you enjoyed your days off! I am following up on the training pipeline implementation. How has it been going? Do you need additional info or material? Thanks for the update.

Hi @JeremyGohBNP, I have opened PRs (#155, #158) for both the training notebooks required in the pipeline, but they haven't been merged yet coz of some recent issues with the CI system. As soon as these are merged, we'll assemble them into a kubeflow pipeline and that would conclude the initial training pipeline implementation.
