### ISSUE TITLE
[EPIC] Update readme to reflect new changes

### ISSUE THREAD

**Issue by Shreyanand** [os-climate/aicoe-osc-demo#162]
All the new changes in the demo2 should be reflected in the Readme section.

Acceptance
- [x] Document the training pipeline notebooks
- [x] Document how to setup a new experiment
- [x] Document how to setup the config files #180
- [x] Fix existing readme issues #160 #159
- [x] #197

**Comment by MichaelTiemannOSC** [comment]
By my own observations, the notebook uses around 27GB of RAM to run, so a minimal notebook seems to be 1 GPU and 32GB RAM.

**Comment by Shreyanand** [comment]
Also add contributors guide for creating PRs on this repo: https://github.com/os-climate/aicoe-osc-demo/pull/166#pullrequestreview-1020345192
