### ISSUE TITLE
[EPIC] User experience 

### ISSUE THREAD

**Issue by Shreyanand** [os-climate/aicoe-osc-demo#193]
The NLP demo is to be transitioned into a public tool and it should have a user friendly workflow around selection of input files, and model parameters. Following issues should be completed:

- [X] Setting up a new experiment #164
- [x] Introduce a settings file #191 
- [x] Define a PDF selection process #192

**Comment by Shreyanand** [comment]
Addressed in #164, #191, #192
