### ISSUE TITLE
[EPIC] Sparsification

### ISSUE THREAD

**Issue by Shreyanand** [os-climate/aicoe-osc-demo#215]
The current relevance and kpi extraction models are huge (0.3gb and 1.3gb respectively) and they take around a total of 15mins to infer for a pdf. We want to find smaller version of the models that get similar performance but using a smaller and faster model.

Overall, we want to investigate model pruning and test the effects of tools such as NeuralMagic to measure the performance impact of different levels of pruning. This EPIC is the first step for this overall goal. 

- [ ] Create time benchmarking notebook
- [ ] Create performance benchmarking notebook
- [ ] Create huggingface version of text classification, relevance task
- [ ] Use sparsified neural models for relevance task
- [ ] Create huggingface version of QA KPI extraction task
- [ ] Use sparsified neural models for KPI extraction task
