### ISSUE TITLE
Demo 1 Ready to Share [Epic]

### ISSUE THREAD

**Issue by MichaelClifford** [os-climate/aicoe-osc-demo#56]
This issue will be used track all outstanding tasks required to complete demo 1. The purpose of this demo is to provide an example and a guide for new users on how to use ODH and OPF to perform data engineering; from collection and ingestion to visualization. 

Demo 1 will include its own directory with a set of notebooks and pipelines needed to ingest data into Trino and Ceph, perform queries and exploration of the data, use pipelines to run recurring ETL, and set up a superset dashboard. It should also include a readme that serves as a walkthrough of the content and workflow. This demo will also include a video recording of the content walkthrough.

Issues:

- [x] Demo notebooks complete #4
- [x] Elyra pipeline defined #13
- [x] Create Superset Dashboard #14
- [x] Readme finished #48
- [x] Video Walkthrough done  #57

**Comment by MichaelClifford** [comment]
All tasks complete!
Video can be seen here https://www.youtube.com/watch?v=TFgsR7UlcHA 
Thanks @aakankshaduggal and @oindrillac :partying_face: Good job!

**Comment by MichaelClifford** [comment]
https://github.com/AICoE/okr/issues/3
