### ISSUE TITLE
Demo 2 Ready to Share [Epic]

### ISSUE THREAD

**Issue by MichaelClifford** [os-climate/aicoe-osc-demo#58]
This issue will be used track all outstanding tasks required to complete demo 2. The purpose of this demo is to provide an example and a guide for new users on how to use ODH and OPF to create an inference pipeline for a NLP model. 

Demo 2 will include its own directory with a set of notebooks, pipelines, serving configurations and documentation needed to run the Allianz/NLP demo. It should also include a README.MD that serves as a walkthrough of the all the content and workflow. This demo will also include a video recording of the content walkthrough.

Issues:

- [x] Table curation and extraction notebooks made  #28 #49
- [x] Text curation and extraction notebooks made #26 #29 
- [x] Create Elyra Pipeline for data curation phase #52
- [x] Docker file creation #45 
- [x] Data in S3 #51
- [x] Add inference notebooks #83 #101 
- [x] Create Elyra pipeline for inference phase #102 #84
- [x] Superset Dashboard #105 
- [x] Readme Finished #61
- [x] Video Walkthrough done #60

**Comment by MichaelClifford** [comment]
https://github.com/AICoE/okr/issues/3

**Comment by MichaelClifford** [comment]
Should we update this epic to reflect the fact that there currently appears to be a resource blocker on training and we've shifted gears a bit to focus on a complete inference pipeline first? 
@Shreyanand @chauhankaranraj @oindrillac
