### ISSUE TITLE
Demo 3 (Connecting Demos 1 & 2) Ready to Share [EPIC]

### ISSUE THREAD

**Issue by MichaelClifford** [os-climate/aicoe-osc-demo#93]
This issue will be used track all outstanding tasks required to complete demo 3. The purpose of this demo is to provide an example and a guide for new users on how to use ODH and OPF for an end-2-end example of data ingestion, preprocessing, model inference, results ingestion into database.  

Demo 3 should be comprised primarily of the existing work completed in demos 1 & 2, and only modified to facilitate the connection of the two previous demo's into a single pipeline or workflow.   

It should also include a README.MD that serves as a walkthrough of the all the content and workflow. This demo will also include a video recording of the content walkthrough.

Issues:

- [ ] Complete demo 2 https://github.com/os-climate/aicoe-osc-demo/issues/58
- [x] Create modified ingestion pipeline from demo 1 to interact with output from demo 2  https://github.com/os-climate/aicoe-osc-demo/issues/94
- [x] Superset Dashboard #105 
- [ ] Readme Finished https://github.com/os-climate/aicoe-osc-demo/issues/96
- [ ] Video Walkththrough done. https://github.com/os-climate/aicoe-osc-demo/issues/95

**Comment by MichaelClifford** [comment]
https://github.com/AICoE/okr/issues/3

**Comment by Shreyanand** [comment]
Demo 2 has been extended to include all the components necessary for an end to end example of data ingestion, preprocessing, model inference, and results ingestion. All the issues are being tracked in this [epic](https://github.com/os-climate/aicoe-osc-demo/issues/58).
